version: '3.8'

services:
  # React Frontend (Production Mode)
  tesseract-caching-editor:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: tesseract-caching-editor
    container_name: tesseract-caching-editor
    ports:
       - "3666:5173"
    command: sh -c "npm run dev -- --host 0.0.0.0"
    #command: sleep infinity
    environment:
      - VITE_PROXY_TARGET=${CACHEFLOW_URL:-http://cacheflow:8000}
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - production-proxy
    networks:
      - proxy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-q", "-T", "10", "http://127.0.0.1:5173/health", "-O", "/dev/null"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.tesseract-frontend.entrypoints=websecure"
      - "traefik.http.routers.tesseract-frontend.tls=true"
      - "traefik.http.routers.tesseract-frontend.tls.certresolver=letsencrypt"
      - "traefik.http.routers.tesseract-frontend.rule=Host(`dev-caching-editor.pscx.ai`)"
      - "traefik.http.services.tesseract-frontend.loadbalancer.server.port=80"
      - "traefik.http.routers.tesseract-frontend-http.entrypoints=web"
      - "traefik.http.routers.tesseract-frontend-http.rule=Host(`dev-caching-editor.pscx.ai`)"
      - "traefik.http.routers.tesseract-frontend-http.middlewares=redirect-to-https"

  # Production Proxy Server (Node.js)
  production-proxy:
    image: node:20-alpine
    container_name: tesseract-production-proxy
    ports:
      - "4011:4011"
    volumes:
      - ./proxy-server.js:/app/proxy-server.js:ro
      - ./package-proxy.json:/app/package.json:ro
      - ./openapi-spec.yaml:/app/openapi-spec.yaml:ro
    working_dir: /app
    command: sh -c "npm install && node proxy-server.js"
    environment:
      - CACHEFLOW_URL=http://host.docker.internal:8000
      - PORT=4011
    networks:
      - proxy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:4011/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) }).on('error', () => process.exit(1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  proxy:
    external: true